on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on:  windows-latest

    steps:
      - name:
        uses: actions/checkout@2

      - name: Deploy to GitHub Pages
        uses: pearceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./